### ISSUE TITLE
Importing harmonist.sidecar first raises ImportError (circular import)

### ISSUE THREAD

**Issue by randomphrase** [randomphrase/harmonist#200]
**Symptom**

`import harmonist.sidecar` as the first `harmonist` import fails:

```
ImportError: cannot import name 'has_sidecar' from partially initialized module
'harmonist.sidecar' (most likely due to a circular import)
```

`import harmonist.url_recovery` fails the same way. Every other module imports fine.

**Root cause**

Introduced by #16. `album_files` imports `sidecar` at module level for `has_sidecar`, and `sidecar` reaches back round:

```
sidecar → library_index → url_recovery → album_files → sidecar
```

Python tolerates the cycle when something *else* is imported first, because `sidecar` is then already fully initialised by the time `album_files` asks for it. That is why the whole test suite, the app, and CI are all green: `harmonist.web.main` and `harmonist.models` always get there first. The cycle only bites when `sidecar` (or `url_recovery`) is the entry point — a one-off script, a REPL, a future module whose import order happens to differ.

Found while writing a standalone script to render an album page, which imported `harmonist.sidecar` on line 1.

**Fix**

`album_files` does not really need `sidecar` — it needs to know whether a directory declares itself an album, which is a filesystem question about a filename. Move `SIDECAR_FILENAME` to `models.py` (which imports nothing from the package) and have both read it from there; `sidecar.py` can re-export it, exactly as it already does for `CURRENT_SCHEMA_VERSION`.

**Worth a guard**, since the failure is invisible to every normal entry point: a test that imports each public module in a fresh subprocess, so any future cycle fails loudly rather than lying in wait for whoever imports in the wrong order.
